# -*- coding: utf-8 -*-
"""LAB_Mapas_18_05_2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VoXETfjRFnVHpa8bMSnZsJLOMq4Aqlyp
"""

import folium
from folium.plugins import minimap
Perez = folium.Map(location=(9.35385948866043, -83.7001219944827))
Perez

from folium.plugins import MiniMap
from branca.element import Figure

popuptext = '<b>Escuela de Informatica</b>'
my_map = folium.Map(location=[9.970875171385705,
 -84.12919600898623],zoom_start=16,tiles='stamenterrain')

folium.Marker(location=[9.970875171385705,
 -84.12919600898623],popup=popuptext,icon=folium.Icon(color="orange",icon="ok-sign")).add_to(my_map)

folium.Circle(location=[9.970875171385705,
 -84.12919600898623],color="purple",weight=6,fill_color="red",fill_opacity=0.5,tooltip="Heredia").add_to(my_map)

minimap = MiniMap(tile_layer='stamenterrain',position='bottomright')

my_map.add_child (minimap)
my_map.save('C:folium.html')
my_map

fig = Figure(width=1000, height=500)
fig.add_child(my_map)
fig